import { createSystem, defaultConfig, defineConfig } from '@chakra-ui/react'

// Кастомизация темы Chakra UI
const customConfig = defineConfig({
    theme: {
        tokens: {
            colors: {
                background: {
                    primary: { value: 'var(--background-primary)' },
                    secondary: { value: 'var(--background-secondary)' },
                    tertiary: { value: 'var(--background-tertiary)' },
                    disabled: { value: 'var(--background-disabled)' },
                    accent: { value: 'var(--background-accent)' },
                    brand: { value: 'var(--background-brand)' },
                    'brand-pressed': { value: 'var(--background-brand-pressed)' },
                    surface: { value: 'var(--extensions-background-surface)' },
                    'inverse-primary': { value: 'var(--extensions-background-inverse-primary)' },
                    'always-dark': { value: 'var(--extensions-background-always-dark)' },
                    'always-light': { value: 'var(--extensions-background-always-light)' },
                    control: { value: 'var(--extensions-background-control)' },
                },
                text: {
                    primary: { value: 'var(--text-and-icon-primary)' },
                    secondary: { value: 'var(--text-and-icon-secondary)' },
                    'on-color': { value: 'var(--text-and-icon-on-color)' },
                    disabled: { value: 'var(--text-and-icon-disabled)' },
                    accent: { value: 'var(--text-and-icon-accent)' },
                    'on-brand': { value: 'var(--extensions-text-and-icon-on-brand)' },
                    'always-dark': { value: 'var(--extensions-text-and-icon-always-dark)' },
                    'always-light': { value: 'var(--extensions-text-and-icon-always-light)' },
                },
                border: {
                    primary: { value: 'var(--border-primary)' },
                    disabled: { value: 'var(--border-disabled)' },
                    accent: { value: 'var(--extensions-border-accent)' },
                    error: { value: 'var(--extensions-border-error)' },
                    success: { value: 'var(--extensions-border-success)' },
                },
                brand: {
                    50: { value: 'var(--extensions-background-light-brand)' },
                    100: { value: 'var(--extensions-background-light-brand)' },
                    200: { value: '#c8e8a0' },
                    300: { value: '#a8d870' },
                    400: { value: '#88c840' },
                    500: { value: 'var(--background-brand)' }, // rgb(20 100 20)
                    600: { value: 'var(--background-brand-pressed)' },
                    700: { value: '#145014' },
                    800: { value: '#0f3a0f' },
                    900: { value: '#0a250a' },
                    DEFAULT: { value: 'var(--background-brand)' },
                    pressed: { value: 'var(--background-brand-pressed)' },
                    light: { value: 'var(--extensions-background-light-brand)' },
                },
                accent: {
                    50: { value: 'var(--extensions-background-light-accent)' },
                    100: { value: 'var(--extensions-background-light-accent)' },
                    200: { value: '#b3d9ff' },
                    300: { value: '#80bfff' },
                    400: { value: '#4da5ff' },
                    500: { value: 'var(--extensions-background-info)' }, // rgb(64 135 225) - синий вместо зелёного
                    600: { value: '#4087e1' },
                    700: { value: '#3065a8' },
                    800: { value: '#20436f' },
                    900: { value: '#102137' },
                    DEFAULT: { value: 'var(--extensions-background-info)' },
                    light: { value: 'var(--extensions-background-light-accent)' },
                },
                success: {
                    50: { value: 'var(--extensions-background-light-success)' },
                    100: { value: 'var(--extensions-background-light-success)' },
                    200: { value: '#b3e6b3' },
                    300: { value: '#80d180' },
                    400: { value: '#4dbc4d' },
                    500: { value: 'var(--extensions-background-success)' }, // rgb(35 178 35)
                    600: { value: '#2a8f2a' },
                    700: { value: '#1f6b1f' },
                    800: { value: '#144714' },
                    900: { value: '#0a230a' },
                    DEFAULT: { value: 'var(--extensions-background-success)' },
                    text: { value: 'var(--extensions-text-and-icon-success)' },
                    light: { value: 'var(--extensions-background-light-success)' },
                },
                error: {
                    50: { value: 'var(--extensions-background-light-error)' },
                    100: { value: 'var(--extensions-background-light-error)' },
                    200: { value: '#ffb3a3' },
                    300: { value: '#ff8066' },
                    400: { value: '#ff4d29' },
                    500: { value: 'var(--extensions-background-error)' }, // rgb(209 61 53)
                    600: { value: '#d13d35' },
                    700: { value: '#9e2e28' },
                    800: { value: '#6b1f1b' },
                    900: { value: '#38100e' },
                    DEFAULT: { value: 'var(--extensions-background-error)' },
                    text: { value: 'var(--extensions-text-and-icon-error)' },
                    light: { value: 'var(--extensions-background-light-error)' },
                },
                warning: {
                    50: { value: 'var(--extensions-background-light-warning)' },
                    100: { value: 'var(--extensions-background-light-warning)' },
                    200: { value: '#ffe6b3' },
                    300: { value: '#ffd480' },
                    400: { value: '#ffc24d' },
                    500: { value: 'var(--extensions-background-warning)' }, // rgb(255 193 60)
                    600: { value: '#cc9a4d' },
                    700: { value: '#99743a' },
                    800: { value: '#664d26' },
                    900: { value: '#332713' },
                    DEFAULT: { value: 'var(--extensions-background-warning)' },
                    text: { value: 'var(--extensions-text-and-icon-warning)' },
                    light: { value: 'var(--extensions-background-light-warning)' },
                },
                info: {
                    50: { value: 'var(--extensions-background-light-accent)' },
                    100: { value: 'var(--extensions-background-light-accent)' },
                    200: { value: '#b3d9ff' },
                    300: { value: '#80bfff' },
                    400: { value: '#4da5ff' },
                    500: { value: 'var(--extensions-background-info)' }, // rgb(64 135 225)
                    600: { value: '#4087e1' },
                    700: { value: '#3065a8' },
                    800: { value: '#20436f' },
                    900: { value: '#102137' },
                    DEFAULT: { value: 'var(--extensions-background-info)' },
                    light: { value: 'var(--extensions-background-light-accent)' },
                },
                additional: {
                    '01': { value: 'var(--additional-background-additional01)' },
                    '02': { value: 'var(--additional-background-additional02)' },
                    '03': { value: 'var(--additional-background-additional03)' },
                    splashscreen: { value: 'var(--additional-background-splashscreen)' },
                },
                overlay: {
                    dark: { value: 'var(--extensions-background-overlay-dark)' },
                    light: { value: 'var(--extensions-background-overlay-light)' },
                },
                primary: {
                    50: { value: '#f0f9ff' },
                    100: { value: '#e0f2fe' },
                    200: { value: '#bae6fd' },
                    300: { value: '#7dd3fc' },
                    400: { value: '#38bdf8' },
                    500: { value: 'var(--background-brand)' },
                    600: { value: 'var(--background-brand-pressed)' },
                    700: { value: '#0369a1' },
                    800: { value: '#075985' },
                    900: { value: '#0c4a6e' },
                },
            },
            // Радиусы скругления
            radii: {
                none: { value: '0' },
                sm: { value: '4px' },
                md: { value: '8px' },
                lg: { value: '12px' },
                xl: { value: '16px' },
                '2xl': { value: '20px' },
                '3xl': { value: '24px' },
                full: { value: '9999px' },
            },
            spacing: {
                0: { value: 'var(--spacers-0)' },
                '2xs': { value: 'var(--spacers-2xs)' },
                xs: { value: 'var(--spacers-xs)' },
                sm: { value: 'var(--spacers-s)' },
                md: { value: 'var(--spacers-m)' },
                lg: { value: 'var(--spacers-l)' },
                xl: { value: 'var(--spacers-xl)' },
                '2xl': { value: 'var(--spacers-2xl)' },
                '3xl': { value: 'var(--spacers-3xl)' },
                '4xl': { value: 'var(--spacers-4xl)' },
                '5xl': { value: 'var(--spacers-5xl)' },
                '6xl': { value: 'var(--spacers-6xl)' },
                '7xl': { value: 'var(--spacers-7xl)' },
                '8xl': { value: 'var(--spacers-8xl)' },
                '9xl': { value: 'var(--spacers-9xl)' },
            },
            fonts: {
                body: { value: 'var(--font-family-noto), system-ui, sans-serif' },
                heading: { value: 'var(--font-family-noto), system-ui, sans-serif' },
                mono: { value: 'monospace' },
            },
            fontSizes: {
                '2xs': { value: 'var(--font-size-xxs)' },
                xs: { value: 'var(--font-size-xs)' },
                sm: { value: 'var(--font-size-s)' },
                md: { value: 'var(--font-size-m)' },
                ml: { value: 'var(--font-size-ml)' },
                lg: { value: 'var(--font-size-l)' },
                xl: { value: 'var(--font-size-xl)' },
                '2xl': { value: 'var(--font-size-xxl)' },
                '3xl': { value: 'var(--font-size-xxxl)' },
            },
            fontWeights: {
                normal: { value: 'var(--font-weight-normal)' },
                regular: { value: 'var(--font-weight-regular)' },
                medium: { value: 'var(--font-weight-medium)' },
                semibold: { value: 'var(--font-weight-semi-bold)' },
                bold: { value: 'var(--font-weight-bold)' },
            },
            lineHeights: {
                xxs: { value: 'var(--line-height-xxs)' },
                xs: { value: 'var(--line-height-xs)' },
                sm: { value: 'var(--line-height-s)' },
                md: { value: 'var(--line-height-m)' },
                ml: { value: 'var(--line-height-ml)' },
                lg: { value: 'var(--line-height-l)' },
                xl: { value: 'var(--line-height-xl)' },
                '2xl': { value: 'var(--line-height-xxl)' },
                '3xl': { value: 'var(--line-height-xxxl)' },
            },
        },
    },
})

export const customSystem = createSystem(defaultConfig, customConfig)

